<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied.' => 'Zugriff verweigert.',
    'Adjective' => 'Adjektiv',
    'Administrator' => 'Administrator',
    'Are you sure you want to delete this item?' => 'Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?',
    'Authentication key' => 'Authentifizierungsschlüssel',
    'Back to home' => 'Zurück zur Startseite',
    'Contact' => 'Kontakt',
    'Copyright' => 'Copyright',
    'Create' => 'Erstellen',
    'Create {modelClass}' => 'Erstelle {modelClass}',
    'Delete' => 'Löschen',
    'DiWA' => 'DiWA',
    'Dictionaries' => 'Wörterbücher',
    'Dictionary' => 'Wörterbuch',
    'Email' => 'E-Mail',
    'Example' => 'Beispiel',
    'FAQ' => 'FAQ',
    'Hash of user agent' => 'Hash des User Agenten',
    'ID' => 'ID',
    'IP address' => 'IP Adresse',
    'If you have questions, please fill out the following form to contact us. Thank you.' => 'Falls Sie Fragen haben, füllen Sie bitte das Kontaktformular aus um uns zu kontaktieren. Vielen Dank.',
    'Imprint' => 'Impressum',
    'Incorrect username or password.' => 'Falscher Benutzername oder falsches Passwort',
    'Invalid request.' => 'Ihre Anfrage ist ungültig.',
    'Language {no}' => 'Sprache {no}',
    'Languages' => 'Sprachen',
    'Last login' => 'Letzer Login',
    'Link' => 'Link',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'No' => 'Nein',
    'Normal User' => 'Normaler Benutzer',
    'Part of speech' => 'Wortart',
    'Password' => 'Passwort',
    'Phrase' => 'Phrase',
    'Please fill out the following fields to login:' => 'Bitte füllen Sie die folgenden Felder aus um sich einzuloggen.',
    'Press <kbd>Esc</kbd> to toggle the navigation menu.' => 'Drücken Sie <kbd>Esc</kbd> um das Navigationsmenü ein- bzw. auszublenden.',
    'Print' => 'Drucken',
    'Remember Me' => 'Anmeldedaten merken',
    'Request' => 'Anfrage',
    'Request time' => 'Anfragezeit',
    'Requested page was not found.' => 'Die angeforderte Seite konnte nicht gefunden werden.',
    'Role' => 'Rolle',
    'Search Request' => 'Suchanfrage',
    'Search Requests' => 'Suchanfragen',
    'Shortname' => 'Kurzname',
    'Statistics' => 'Statistik',
    'Substantive' => 'Substantiv',
    'Terminologist' => 'Terminologe',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Vielen Dank, dass Sie uns kontaktieren. Wir werden Ihnen so schnell wie möglich antworten.',
    'The authors are: {ppl1} and {ppl2}(Design).' => 'Die Autoren sind: {ppl1} und {ppl2}(Design).',
    'This application is licensed with the GNU General Public License Version 3' => 'Diese Anwendung wurde mit der GNU General Public License Version 3 lizensiert.',
    'This site has been created with the following tools and ressources:' => 'Diese Seite wurde mit Hilfe der folgenden Ressourcen entwickelt und erstellt:',
    'Translate' => 'Übersetzen',
    'Translations' => 'Übersetzungen',
    'Unknown Words' => 'Unbekannte Wörter',
    'Update' => 'Aktualisieren',
    'Update {modelClass}: ' => 'Aktualisiere {modelClass}',
    'User Agents' => 'User Agents',
    'User agent' => 'User Agent',
    'Username' => 'Benutzername',
    'Users' => 'Benutzer',
    'Verb' => 'Verb',
    'Website' => 'Webseite',
    'Word' => 'Wort',
    'Word {no}' => 'Wort {no}',
    'Yes' => 'Ja',
    'Your message' => 'Ihre Nachricht',
    'name' => 'Name',
];
