<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login' => 'Login',
    'Access denied.' => 'Zugriff verweigert.',
    'Administrator' => 'Administrator',
    'Authentication key' => 'Authentifizierungsschlüssel',
    'Contact' => 'Kontakt',
    'Copyright' => 'Copyright',
    'DiWA' => 'DiWA',
    'Dictionary' => 'Wörterbuch',
    'Hash of user agent' => 'Hash des User Agenten',
    'ID' => 'ID',
    'IP address' => 'IP Adresse',
    'Imprint' => 'Impressum',
    'Invalid request.' => 'Ihre Anfrage ist ungültig.',
    'Language {no}' => 'Sprache {no}',
    'Last login' => 'Letzer Login',
    'Logout' => 'Logout',
    'Name' => 'Benutzer',
    'No' => 'Nein',
    'Normal User' => 'Normaler Benutzer',
    'Part of speech' => 'Wortart',
    'Password' => 'Passwort',
    'Press <kbd>Esc</kbd> to toggle the navigation menu.' => 'Drücken Sie <kbd>Esc</kbd> um das Navigationsmenü ein- bzw. auszublenden.',
    'Print' => 'Drucken',
    'Request' => 'Anfrage',
    'Request time' => 'Anfragezeit',
    'Requested page was not found.' => 'Die angeforderte Seite konnte nicht gefunden werden.',
    'Role' => 'Rolle',
    'Shortname' => 'Kurzname',
    'Terminologist' => 'Terminologe',
    'User agent' => 'User Agent',
    'Username' => 'Benutzername',
    'Word' => 'Wort',
    'Word {no}' => 'Wort {no}',
    'Yes' => 'Ja',
    'name' => 'Name',
];
